name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  terraform:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infrastructure/dev/aws

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Initialize TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint

      - name: Install tfsec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: Run tfsec
        run: tfsec --soft-fail .

      - name: Install Checkov
        run: |
          python -m pip install --upgrade pip
          pip install checkov

      - name: Run Checkov
        run: checkov -d . --soft-fail
